language: java
jdk: oraclejdk8
# Run on a dedicated Trusty VM to avoid random problems like "User limit of inotify watches reached"
sudo: required
dist: trusty

addons:
  chrome: stable

services:
  - docker

before_install: ./.travis.before_install.sh

# Skip the installation step.
# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true

script: ./.travis.script.sh

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
before_cache:
  # remove all build artifacts
  - rm -rf $TRAVIS_BUILD_DIR/localrepo/com/vaadin/flow
  - rm -rf $TRAVIS_BUILD_DIR/localrepo/com/vaadin/flow-*
after_failure: ./.travis.after_failure.sh
