version: '3'
services:
  flow-patient-portal:
    build: .
    ports:
      - 80:8080
    environment:
      - spring.datasource.url=jdbc:mysql://$datasourceUrl:3306/pp
    image:
      'repo.vaadin.com:5001/flow-patient-portal:tomcat'
